package staticembed

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// tinyTokenizer is a hand-built WordPiece vocabulary: ids are chosen so the
// synthetic embedding table below is easy to reason about.
const tinyTokenizer = `{
  "normalizer": {"type": "BertNormalizer", "clean_text": true, "handle_chinese_chars": true, "strip_accents": null, "lowercase": true},
  "pre_tokenizer": {"type": "BertPreTokenizer"},
  "model": {"type": "WordPiece", "unk_token": "[UNK]", "continuing_subword_prefix": "##", "max_input_chars_per_word": 100,
    "vocab": {"[PAD]": 0, "[UNK]": 1, "wall": 2, "##s": 3, "create": 4, ".": 5, "level": 6, "##2": 7, "cafe": 8}}
}`

// tinySafetensors builds a [9, 2] F32 "embeddings" tensor where row i is (i, 1).
func tinySafetensors(t *testing.T) []byte {
	t.Helper()
	header, _ := json.Marshal(map[string]any{
		"embeddings": map[string]any{"dtype": "F32", "shape": []int{9, 2}, "data_offsets": []int{0, 9 * 2 * 4}},
	})
	b := make([]byte, 8)
	binary.LittleEndian.PutUint64(b, uint64(len(header)))
	b = append(b, header...)
	for i := 0; i < 9; i++ {
		for _, x := range []float32{float32(i), 1} {
			var u [4]byte
			binary.LittleEndian.PutUint32(u[:], math.Float32bits(x))
			b = append(b, u[:]...)
		}
	}
	return b
}

func TestTokenizeMirrorsModel2Vec(t *testing.T) {
	m, err := Load([]byte(tinyTokenizer), tinySafetensors(t), true)
	if err != nil {
		t.Fatal(err)
	}
	cases := []struct {
		in   string
		want []int
	}{
		{"Wall", []int{2}},                       // lowercased
		{"walls", []int{2, 3}},                   // greedy longest match + ##suffix
		{"Wall.Create", []int{2, 5, 4}},          // punctuation is its own word
		{"Level2", []int{6, 7}},                  // digit continuation piece
		{"café", []int{8}},                       // accent stripped via NFD
		{"zzz wall", []int{2}},                   // unknown word dropped, not emitted as [UNK]
		{"  wall\tcreate\n", []int{2, 4}},        // whitespace folding
		{"", nil},                                // nothing
		{"walls" + string(rune(0)), []int{2, 3}}, // control chars removed
	}
	for _, c := range cases {
		got := m.Tokenize(c.in)
		if len(got) == 0 {
			got = nil
		}
		if !reflect.DeepEqual(got, c.want) {
			t.Errorf("Tokenize(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestEmbedIsNormalisedMeanOfRows(t *testing.T) {
	m, err := Load([]byte(tinyTokenizer), tinySafetensors(t), true)
	if err != nil {
		t.Fatal(err)
	}
	if m.Dim() != 2 {
		t.Fatalf("Dim = %d", m.Dim())
	}
	vs, err := m.Embed(context.Background(), []string{"wall create", "zzz", "walls"})
	if err != nil {
		t.Fatal(err)
	}
	// rows 2=(2,1), 4=(4,1) -> mean (3,1) -> normalised
	n := float32(math.Sqrt(10))
	if want := []float32{3 / n, 1 / n}; !approx(vs[0], want) {
		t.Errorf("wall create = %v, want %v", vs[0], want)
	}
	if !approx(vs[1], []float32{0, 0}) {
		t.Errorf("unknown-only text should embed to zero, got %v", vs[1])
	}
	// rows 2=(2,1), 3=(3,1) -> (2.5, 1)
	n = float32(math.Sqrt(2.5*2.5 + 1))
	if want := []float32{2.5 / n, 1 / n}; !approx(vs[2], want) {
		t.Errorf("walls = %v, want %v", vs[2], want)
	}
}

func TestLoadRejectsMismatchedVocabAndTable(t *testing.T) {
	bad := tinySafetensors(t)
	// Claim 8 rows for a 9-token vocab: header says [8,2] with matching bytes.
	header, _ := json.Marshal(map[string]any{
		"embeddings": map[string]any{"dtype": "F32", "shape": []int{8, 2}, "data_offsets": []int{0, 8 * 2 * 4}},
	})
	b := make([]byte, 8)
	binary.LittleEndian.PutUint64(b, uint64(len(header)))
	b = append(b, header...)
	b = append(b, bad[len(bad)-8*2*4:]...)
	if _, err := Load([]byte(tinyTokenizer), b, true); err == nil {
		t.Fatal("expected a vocab/table size mismatch error")
	}
}

// TestParityWithPythonModel2Vec checks token ids and vectors against
// reference output from the Python model2vec package for potion-base-8M.
// It needs the real model files; point SEMSEARCH_POTION_DIR at a directory
// holding tokenizer.json, model.safetensors and parity.json (generated by
// the POC's parity script), otherwise it is skipped.
func TestParityWithPythonModel2Vec(t *testing.T) {
	dir := os.Getenv("SEMSEARCH_POTION_DIR")
	if dir == "" {
		t.Skip("SEMSEARCH_POTION_DIR not set")
	}
	tok, err := os.ReadFile(filepath.Join(dir, "tokenizer.json"))
	if err != nil {
		t.Fatal(err)
	}
	st, err := os.ReadFile(filepath.Join(dir, "model.safetensors"))
	if err != nil {
		t.Fatal(err)
	}
	m, err := Load(tok, st, true)
	if err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "parity.json"))
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Text   string    `json:"text"`
		Tokens []int     `json:"tokens"`
		Vec    []float32 `json:"vec"`
	}
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		got := m.Tokenize(c.Text)
		if len(got) == 0 {
			got = nil
		}
		want := c.Tokens
		if len(want) == 0 {
			want = nil
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("Tokenize(%q) = %v, want %v", c.Text, got, want)
		}
		vs, _ := m.Embed(context.Background(), []string{c.Text})
		if cos := cosine(vs[0], c.Vec); cos < 0.9999 && !(isZero(vs[0]) && isZero(c.Vec)) {
			t.Errorf("Embed(%q) cosine to Python = %.6f", c.Text, cos)
		}
	}
}

func approx(a, b []float32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if math.Abs(float64(a[i]-b[i])) > 1e-5 {
			return false
		}
	}
	return true
}

func cosine(a, b []float32) float64 {
	var dot, na, nb float64
	for i := range a {
		dot += float64(a[i] * b[i])
		na += float64(a[i] * a[i])
		nb += float64(b[i] * b[i])
	}
	if na == 0 || nb == 0 {
		return 0
	}
	return dot / math.Sqrt(na*nb)
}

func isZero(v []float32) bool {
	for _, x := range v {
		if x != 0 {
			return false
		}
	}
	return true
}
